_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

BluegrassBluesWidgetBundle:
    resource: "@BluegrassBluesWidgetBundle/Resources/config/routing.yml"
    prefix:   /
